food_for_thought/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from recipes import views

urlpatterns = [
                  path('', views.home, name='home'),
                  path('recipes/', include('recipes.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from recipes import views

app_name = "recipes"

urlpatterns = [
    path('', views.home, name='home'),
    path('categories/', views.categories, name='categories'),
    path('categories/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('results/', views.show_results, name='show_results'),
    path('<int:user_id>/', views.show_non_user_account, name='show_non_user_account'),
    path('<int:user_id>/recipes/', views.show_non_user_recipes, name='show_non_user_recipes'),
    path('<int:user_id>/<slug:recipe_name_slug>/', views.show_recipe, name='show_recipe'),
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('myaccount/', views.show_user_account, name='show_user_account'),
    path('myaccount/myrecipes/', views.show_user_recipes, name='show_user_recipes'),
    path('myaccount/addrecipe/', views.add_recipe, name='add_recipe'),
    path('myaccount/myreviews/', views.show_user_reviews, name='show_user_reviews'),
    path('myaccount/mysavedrecipes', views.show_user_saved_recipes, name='show_user_saved_recipes'),
    path('myaccount/editaccount/', views.edit_account, name='edit_account'),
    path('myaccount/deleteaccount/', views.delete_account, name='delete_account'),
    path('myaccount/editreview/<int:review_id>/', views.edit_review, name='edit_review'),
    path('myaccount/deletereview/<int:review_id>/', views.delete_review, name='delete_review'),
    path('myaccount/editrecipe/<int:recipe_id>/', views.edit_recipe, name='edit_recipe'),
    path('myaccount/deleterecipe/<int:recipe_id>/', views.delete_recipe, name='delete_recipe'),
    path('myaccount/togglesaverecipe/<int:recipe_id>/', views.toggle_save_recipe, name='toggle_save_recipe'),
    path('fetch_cats/', views.fetch_cats, name="fetch_cats"),
    path('fetch_author/', views.fetch_author, name="fetch_author"),
]

recipes/forms.py
from django import forms
from django.contrib.auth.models import User
from recipes.models import Recipe, UserProfile, Review, Category

from datetime import timedelta


class CookingTimeField(forms.FloatField):
    def clean(self, value):
        data = super().clean(value)
        if data:
            return timedelta(hours=data)
        else:
            return timedelta()


class RecipeForm(forms.ModelForm):
    title = forms.CharField(max_length=100)
    title.widget.attrs.update({"class": "form-control", "placeholder": "Name of Recipe"})

    image = forms.ImageField(help_text="Upload Image: ")
    image.widget.attrs.update({"class": "form-control", "placeholder": "Upload an image"})

    category = forms.ModelMultipleChoiceField(Category.objects.all(), required=False)
    category.widget.attrs.update({ "id": "categoryInput", "multiple": "multiple"})

    content = forms.CharField(max_length=10000, widget=forms.Textarea(attrs={"class": "form-control", "rows": "8", "placeholder": "Method"}))

    ingredients = forms.CharField(max_length=10000, widget=forms.Textarea(attrs={"class": "form-control", "rows": "8", "placeholder": "Ingredients"}))

    servings = forms.IntegerField(label="Servings", min_value=1)
    servings.widget.attrs.update({"class": "form-control", "placeholder": "Number of Servings"})

    cooking_time = CookingTimeField(label="Cooking Time")
    cooking_time.widget.attrs.update({"class": "form-control", "step": "0.01"})

    tags = forms.CharField(max_length=1000, help_text="Tags (optional): ", required=False)
    tags.widget.attrs.update({"class": "form-control", "placeholder": "Tags (Optional)"})

    class Meta:
        model = Recipe
        exclude = ('author', 'slug')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    firstname = forms.CharField(required=False)
    lastname = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'firstname', 'lastname')


class UserProfileForm(forms.ModelForm):
    picture = forms.ImageField(required=False)
    bio = forms.CharField(required=False)

    class Meta:
        model = UserProfile
        fields = ('picture', 'bio',)


class ReviewForm(forms.ModelForm):
    content = forms.CharField(max_length=1000, help_text="Enter your thoughts on the recipe.")
    rating_choices = [(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
    rating = forms.ChoiceField(widget=forms.RadioSelect(), choices=rating_choices, required=False)

    class Meta:
        model = Review
        exclude = ('author', 'recipe',)

class SearchForm(forms.Form):
    category = forms.ModelMultipleChoiceField(Category.objects.all(), label = "Categories", required=False)
    category.widget.attrs.update({"id": "categoryInput", "multiple": "multiple"})

    time = CookingTimeField(label="Max time in hours", required = False)
    time.widget.attrs.update({"class": "form-control", "step": "0.01"})

    author = forms.ModelChoiceField(UserProfile.objects.all(), required=False)
    author.widget.attrs.update({"id": "authorInput"})

    sort = forms.ChoiceField(choices=(('rd', "Rating Descending"), ('ra', "Rating Ascending"), ('aa', "Alphabetical"), ('ad', "Reverse Alphabetical")))
    sort.widget.attrs.update({"class": "form-select"})

recipes/views.py
from django.core.exceptions import ValidationError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.db.models import Avg, Count, Q

from recipes.models import Category, Recipe, Review, UserProfile
from recipes.forms import UserForm, UserProfileForm, RecipeForm, ReviewForm, SearchForm

from datetime import timedelta


def home(request):
    category_list = Category.objects.annotate(number_of_recipes=Count('recipe')).order_by('-number_of_recipes')[:4]
    recipe_list = Recipe.objects.annotate(average_rating=Avg('review__rating')).order_by('-average_rating')[:4]

    context_dict = {'categories': category_list, 'recipes': recipe_list}

    return render(request, 'recipes/home.html', context=context_dict)


def categories(request):
    category_list = Category.objects.annotate(number_of_recipes=Count('recipe')).order_by('-number_of_recipes')

    context_dict = {'categories': category_list}

    return render(request, 'recipes/categories.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    category = get_object_or_404(Category, slug=category_name_slug)
    recipes = Recipe.objects.annotate(average_rating=Avg('review__rating')).filter(category=category).distinct()

    context_dict['category'] = category
    context_dict['recipes'] = recipes

    return render(request, 'recipes/category.html', context=context_dict)


def show_results(request):
    req = request.GET.get('q', default="")
    req_words = set(req.split())

    form = SearchForm(request.GET)
    context_dict = {"req": req, "form": form, "results": None}

    query = Q()
    for word in req_words:
        query |= Q(title__icontains=word) | Q(ingredients__icontains=word) | Q(tags__icontains=word)

    if form.is_valid():
        categories = form.cleaned_data['category']
        time = form.cleaned_data['time']
        author = form.cleaned_data['author']
        sort = form.cleaned_data['sort']

        if categories.exists():
            query &= Q(category__in=categories)

        if time:
            query &= Q(cooking_time__lte=time)

        if author:
            query &= Q(author=User.objects.get(userprofile=author))

        results = Recipe.objects.filter(query).annotate(average_rating=Avg('review__rating'))

        sorts = {
            'rd': '-average_rating',
            'ra': 'average_rating',
            'aa': 'title',
            'ad': '-title'
        }
        if sort:
            results = results.order_by(sorts[sort])

        context_dict["results"] = results

    return render(request, 'recipes/results.html', context=context_dict)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('recipes:home'))
            else:
                context_dict = {'message': 'Your Food For Thought account is disabled'}
        else:
            print(f"Invalid login details: {username}, {password}")
            context_dict = {'message': 'Invalid login details given, please enter valid details'}

        return render(request, "recipes/login.html", context=context_dict)

    else:
        context_dict = {'message': None}
        return render(request, "recipes/login.html", context=context_dict)


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('recipes:home'))


def sign_up(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context_dict = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}

    return render(request, 'recipes/signup.html', context=context_dict)


def show_recipe(request, user_id, recipe_name_slug):
    context_dict = {}

    recipe = get_object_or_404(Recipe, slug=recipe_name_slug, author=User.objects.get(id=user_id))
    average_rating = Review.objects.filter(recipe=recipe).aggregate(Avg('rating'))['rating__avg']
    reviews = Review.objects.filter(recipe_id=recipe.id)

    context_dict['recipe'] = recipe
    context_dict['average_rating'] = average_rating
    context_dict['reviews'] = reviews
    if request.user.is_authenticated and not Review.objects.filter(author=request.user,
                                                                   recipe=recipe).exists() and not recipe.author == request.user:
        form = ReviewForm()

        if request.method == "POST":
            form = ReviewForm(request.POST)

            if form.is_valid():
                review = form.save(commit=False)
                review.author = request.user
                review.recipe = recipe
                review.save()

                return redirect(reverse('recipes:show_recipe', args=[user_id, recipe_name_slug]))
            else:
                print(form.errors)

        context_dict['review_form'] = form

    return render(request, 'recipes/recipe.html', context=context_dict)


@login_required
def show_user_account(request, msg=None):
    if msg is None:
        current_user = request.user

        current_user_profile = UserProfile.objects.get(user=current_user)

        saved_recipes_ratings = current_user_profile.saved.annotate(average_rating=Avg('review__rating')).order_by('-average_rating')[:4]

        written_recipes = Recipe.objects.filter(author=current_user).annotate(average_rating=Avg('review__rating')).order_by('-average_rating')[:4]

        written_reviews = Review.objects.filter(author=current_user)[:4]

        context_dict = {"current_user": current_user_profile, "saved_recipes": saved_recipes_ratings,
                        "written_recipes": written_recipes,
                        "written_reviews": written_reviews}

        return render(request, 'recipes/my_account.html', context=context_dict)

    else:
        return HttpResponse(msg)


@login_required
def add_recipe(request):
    form = RecipeForm()

    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES)

        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user

            if 'image' in request.FILES:
                recipe.image = request.FILES['image']

            recipe.save()

            recipe.category.add(*form.cleaned_data['category'])

            return redirect(reverse('recipes:show_user_account'))
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'recipes/add_recipe.html', context=context_dict)


@login_required
def show_user_recipes(request):
    current_user = request.user

    written_recipes = Recipe.objects.filter(author=current_user)

    written_recipes = written_recipes.annotate(average_rating=Avg('review__rating'))

    context_dict = {'written_recipes': written_recipes}

    return render(request, 'recipes/my_recipes.html', context=context_dict)


@login_required
def show_user_reviews(request):
    current_user = request.user

    written_reviews = Review.objects.filter(author=current_user)

    context_dict = {'written_reviews': written_reviews}

    return render(request, 'recipes/my_reviews.html', context=context_dict)


@login_required
def show_user_saved_recipes(request):
    current_user = request.user

    current_user_profile = UserProfile.objects.get(user=current_user)

    saved_recipes = current_user_profile.saved.annotate(average_rating=Avg('review__rating')).order_by(
        '-average_rating')

    context_dict = {'saved_recipes': saved_recipes}

    return render(request, 'recipes/saved_recipes.html', context=context_dict)


def show_non_user_account(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if user == request.user:
        return redirect(reverse('recipes:show_user_account'))

    user_profile = UserProfile.objects.get(user=user)

    written_recipes = Recipe.objects.filter(author=user).annotate(average_rating=Avg('review__rating')).order_by('-average_rating')[:4]

    written_reviews = Review.objects.filter(author=user)[:3]

    context_dict = {"account_user": user, "written_recipes": written_recipes,
                    "written_reviews": written_reviews, "user_profile": user_profile}
    return render(request, 'recipes/others_account.html', context=context_dict)


def show_non_user_recipes(request, user_id):
    user = get_object_or_404(User, id=user_id)
    written_recipes = Recipe.objects.filter(author=user).annotate(average_rating=Avg('review__rating')).order_by('-average_rating')[:4]

    context_dict = {'written_recipes': written_recipes, "account_user": user}

    return render(request, 'recipes/others_recipes.html', context=context_dict)


@login_required
def edit_account(request):
    edited = False

    user_profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)

templates/recipes/add_recipe.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Create a recipe
{% endblock %}

{% block body_block %}
<div>
    <h1>Add a Recipe</h1><br>
    <form enctype="multipart/form-data" id="recipe_form" method="POST" action="{% url 'recipes:add_recipe' %}">
        {% include 'recipes/recipe_form.html' with form=form %}
        <div class="text-center">
            <button type="submit" name="submit" value="Create recipe" class="btn btn-outline-success">Create Recipe</button>
        </div>
    </form>
</div>
{% endblock %}

templates/recipes/card_grid.html
{% for card in cards %}
{% if forloop.counter0|divisibleby:4 %}
<div class="row row-cols-1 row-cols-lg-4 g-4 pb-4">
{% endif %}

    <div class="col">
        {% block card_content %}
        {% endblock %}
    </div>

{% if forloop.counter|divisibleby:4 or forloop.last %}
</div>
{% endif %}

{% endfor %}

templates/recipes/categories.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class = "container text-center mt-5">
    <h1>Categories</h1><br><br>
    {% if categories %}
    {% include 'recipes/category_grid.html' with cards=categories %}
    {% else %}
    <strong>There are no categories present.</strong>
    {% endif %}
</div>
{% endblock %}

templates/recipes/category_card.html
<div class="card h-100">

<img src="{{ category.image.url }}" class="card-img-top object-fit-cover" height="250" alt="{{ category.name }} image">
<div class="card-body text-start">
    <h5 class="card-title"><a href="{% url 'recipes:show_category' category.slug %}">{{ category.name }}</a></h5>
    <p class="card-text">{{ category.description }}</p>

</div>
<div class="card-footer">
    <p class="card-text"><small class="text-muted">{{ category.number_of_recipes }} recipe{{ category.number_of_recipes|pluralize }}</small></p>
</div>

</div>

templates/recipes/category_grid.html
{% extends 'recipes/card_grid.html' %}

{% block card_content %}
    {% include 'recipes/category_card.html' with category=card %}
{% endblock %}

templates/recipes/comment_card.html
{% load recipes_template_tags %}
<div class="card mb-4 mx-auto w-50" id="review{{ review.id }}">
    <div class="card-body">
        <h5 class="card-title"><a href="{% url 'recipes:show_recipe' review.recipe.author.id review.recipe.slug %}">{{ review.recipe.title }}</a></h5>
        <p class="card-text">
        {{ review.content }} <br>
        Rating: <i class="bi bi-star-fill text-warning"></i> {{ review.rating }}
        </p>
    </div>
    {% if request.user == review.author %}
    <div class="card-footer">
        <div class="btn-group" role="group">
            <a href="{% url 'recipes:edit_review' review.id %}" class="btn btn-outline-success">Edit</a>
            {% confirm_review_deletion review %}
        </div>
    </div>
    {% endif %}
</div><br>

templates/recipes/edit_review.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Edit Review
{% endblock %}

{% block body_block %}
<h1 class="text-center fftTitle">Edit Review For <a href="{% url 'recipes:show_recipe' recipe.author.id recipe.slug %}">{{ recipe.title }}</a></h1>
<div>
    <form id="review_form" method="POST" action="{% url 'recipes:edit_review' review.id %}" enctype="multipart/form-data">
        <div class="row">
            {% csrf_token %}
            <div class="rating col-sm-3">
                {% for val in values %}
                    {% if val == checked_val %}
                        <input type="radio" name="rating" value="{{ val }}" id="{{ checked_val }}" checked><label for="{{ checked_val }}">☆</label>
                    {% else %}
                        <input type="radio" name="rating" value="{{ val }}" id="{{ val }}"><label for="{{ val }}">☆</label>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="form-floating mb-3 col">
                <textarea class="form-control border border-success border-3 opacity-75" placeholder="Leave a comment here" id="floatingTextarea" name="content">{{ review.content }}</textarea>
                <label for="floatingTextarea">Comments</label>
            </div>
        </div>
        <div class="text-center">
            <button class="btn btn-outline-success" type="submit" name="submit" value="Update review">Update Review</button>
        </div>
    </form>
</div>
{% endblock %}

templates/recipes/home.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class = "container text-center">
    <h1 class="fftTitle">Food For Thought</h1>
    <p class="lead mt-5">
      Welcome to Food For Thought! A dynamic recipe website that allows you to easily share, find and save your favourite recipes.
    </p><br>

    <hr class="border border-success border-3 opacity-75 mb-5 mt-5">

    <div>
       <h2><a href="{% url 'recipes:categories' %}">Categories</a></h2><br><br>
    {% if categories %}
        {% include 'recipes/category_grid.html' with cards=categories %}
    {% else %}
       <strong>There are no categories present.</strong>
    {% endif %}
    </div>

    <hr class="border border-success border-3 opacity-75 mb-5 mt-5">

    <div>
       <br><h2>Highest Rated Recipes</h2><br><br>
    {% if recipes %}
        {% include 'recipes/recipe_grid.html' with cards=recipes %}
    {% else %}
       <strong>There are no recipes present.</strong>
    {% endif %}
    </div>
</div>
{% endblock %}

templates/recipes/others_account.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class = "container text-center mt-5">
    <div class="row mb-5">
        <div class="col">
            <div class="card w-75">
                <img src="{{ user_profile.picture.url }}" class="img-thumbnail rounded float-start" alt="Profile image">
            </div>
        </div>
        <div class="col">
            <div class="card w-75 border-success border-3">
                <div class="card-body">
                    <h2 class="card-title">{{ account_user.username }}</h2><br>
                    <p class="card-text">
                        <b>Name:</b> {{ account_user.first_name }} {{ account_user.last_name }}<br>
                        <b>Email:</b> {{ account_user.email }}<br>
                        <b>Bio:</b> {{ user_profile.bio }}
                    </p>
                </div>
            </div>
        </div>
    </div>



    {% if written_recipes %}
    <hr class="border border-success border-3 opacity-75 mb-5">
    <div class="row mb-5">
        <div class="col align-items-center">
           <h2><a href="{% url 'recipes:show_non_user_recipes' account_user.id %}">{{ account_user.username }}'s Recipes</a></h2><br><br>
            {% include 'recipes/recipe_grid.html' with cards=written_recipes %}
        </div>
    </div>
    {% endif %}

    {% if written_reviews %}
    <hr class="border border-success border-3 opacity-75 mb-5">
    <div class="row mb-5">
        <div class="col">
            <h2>{{ account_user.username }}'s Reviews</h2><br><br>
            {% for review in written_reviews %}
                {% include 'recipes/comment_card.html' with review=review %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/recipes/recipe_grid.html
{% extends 'recipes/card_grid.html' %}

{% block card_content %}
    {% include 'recipes/recipe_card.html' with recipe=card %}
{% endblock %}

templates/recipes/results.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="container">
    <form role="search" action="./" method="get">
        <div class="input-group mb-3 w-50 mx-auto">
            <input type="search" name="q" value="{{ req }}" placeholder="Search" class="form-control">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </div>
        <div class="mb-3 mt-4 row">
            {% for field in form %}
            <div class="col input-group">
                {{ field.errors }}
                <span class="input-group-text">{{ field.label }}</span>
                {{ field }}
            </div>
            {% endfor %}
        </div>
    </form>
</div>

<div class="container mt-5">
    <hr class="border border-success border-3 opacity-75 mb-5 mt-5">
    {% if results %}
        <h2>Results for "{{ req }}":</h2><br><br>
        {% include 'recipes/recipe_grid.html' with cards=results %}
    {% else %}
    <h2>No results.</h2>
    {% endif %}
</div>

{% endblock %}

templates/recipes/saved_recipes.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class = "container text-center mt-5">
    <h1>Your Saved Recipes</h1><br><br>
    {% if saved_recipes %}
        {% include 'recipes/recipe_grid.html' with cards=saved_recipes %}
    {% else %}
        <strong>There are no recipes present.</strong>
    {% endif %}
</div>
{% endblock %}

templates/recipes/toggle_save_button.html
{% if request.user.is_authenticated %}
<div id="saveRecipeButton{{ recipe.id }}">
<button onclick="ajaxHelper('{% url 'recipes:toggle_save_recipe' recipe.id %}')"class="btn 
{% if recipe not in request.user.userprofile.saved.all %} btn-success">Save
{% else %} 
btn-danger">Unsave
{% endif %}
Recipe</button> 
</div>
{% endif %}

templates/recipes/update_profile.html
{% extends 'recipes/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Edit Account
{% endblock %}

{% block body_block %}
<div class="row justify-content-md-center">
    <div class="col col-lg-4">
        <h1>Edit Account</h1><br>
        <div>
            {% if edited %}
                 <strong>Changes saved.</strong>
                 <a href="{% url 'recipes:login' %}">Please log back in.</a><br />
            {% endif %}
            <br>
            <form id="user_form" method="post" action="{% url 'recipes:edit_account' %}" enctype="multipart/form-data">
                {% csrf_token %}

                {% if user_form.errors or profile_form.errors %}
                    <div class="alert alert-danger">
                        {{ user_form.errors }}
                        {{ profile_form.errors }}
                    </div>
                 {% endif %}

                <div class = "mb-3">
                    <input type="text" class="form-control" name="username" value="{{ user.get_username }}" placeholder="Username" >
                </div>

                <div class = "mb-3">
                    <input type="text" class="form-control" name="firstname" value="{{ user.first_name }}" placeholder="First Name" >
                </div>

                <div class = "mb-3">
                    <input type="text" class="form-control" name="lastname" value="{{ user.last_name }}" placeholder="Last Name" >
                </div>

                <div class = "mb-3">
                    <input type="email" class="form-control" name="email" value="{{ user.email }}" placeholder="Email Address" >
                </div>

                <div class = "mb-3">
                    <input type="password" class="form-control" name="password" placeholder="Password" >
                </div>

                <div class="input-group mb-3">
                    <input type="file" class="form-control" name="picture" value="{{ user.userprofile.picture }}" >
                    <button class="btn btn-danger" formaction="{{ user.userprofile.picture.clear }}" value="Remove pic">Remove pic</button>
                </div>

                <div class="input-group">
                    <label class="input-group-text" for="bioInput">Bio</label>
                    <textarea class="form-control" name="bio" id="bioInput" placeholder="Tell us a bit about yourself...">{{ user.userprofile.bio }}</textarea>
                </div>

                <br><br>

                <div class="text-center">
                    <button type="submit" name="submit" value="Save Changes" class="btn btn-success">Save Changes</button>
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}